# Numpy Exercise 5

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
#The rougier/numpy-100 is a collection of 100 excuses focused on the numpy library
import numpy as np


#### 61. Find the nearest value from a given value in an array (★★☆)

In [2]:
data = np.array([1,2,3,5,6,7])
target = 4

nearest_value = min(data, key=lambda x: abs(x-target))
print(nearest_value)

3


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [3]:
#Example of broadcasting where the second array is replicated to match the she of the first one
A = np.array([[1,2,3]])
B = np.array([[1],[2],[3]])

print(A.shape)
print(B.shape)

print(A + B)


(1, 3)
(3, 1)
[[2 3 4]
 [3 4 5]
 [4 5 6]]


#### 63. Create an array class that has a name attribute (★★☆)

In [4]:
my_array = np.array([1, 2, 3, 4, 5])
array_name = "arrayname"

print(my_array)
print(array_name)


[1 2 3 4 5]
arrayname


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [5]:
# A vector is also a 1D array
# We use fancy indexing to get the elements in the array for indices 0,2 & 4 and add 1 to each

arr = np.array([10, 20, 30, 40, 50])

idx = np.array([0, 1, 2, 3, 4])

arr[idx] += 1

print(arr)

[11 21 31 41 51]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [6]:
#add.at is a universal function where the arrays are added based on the index specified
X = np.array([1, 2, 3, 4])

l = np.array([1, 2, 3, 4])

F = np.array([10, 20, 30, 40, 50, 60])

np.add.at(F, l, X)

print(F)


[10 21 32 43 54 60]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [7]:
#w, h, 3 means the width, height and 3 for the color Channels(Red, Green, Blue)
#data type ubyte = unsigned 8-bit integer where value range from 0 to 255
#The np.unique only worsk on rows that why we reshape the array
#The pixel is a set of unique colors
image = np.array([
                 [[255,0,0],[0,255,0]],
                 [[0,0,255], [255,0,0]]
                 ])
pixels = image.reshape(-1, 3)

unique_colors = np.unique(pixels, axis =0)
print(len(unique_colors))


3


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [8]:
#Instead of hardcoding everything, just create an array with arange and then shape it
fourD_Array = np.arange(1,25).reshape(2,2,2,3)

print(fourD_Array)

sum_result = fourD_Array.sum(axis=(2,3))

print(sum_result)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]]]]
[[ 21  57]
 [ 93 129]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [9]:
#lets start off with vector D
D = np.array([10, 20, 30, 40, 50, 60])
#vectors s describing subset indices
S = np.array([0, 0, 1, 1, 2, 2])
#The unique gets the unique gruops i.e with the same indices and assigns them to variable groups
groups = np.unique(S)

means = np.array([D[S == g].mean() for g in groups])

print(means)

[15. 35. 55.]


#### 69. How to get the diagonal of a dot product? (★★★)

In [10]:
""" a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a.dot(b)

d = np.diag(c)
print(c) """

a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[10,11,12],
              [13,14,15],
              [16,17,18]])

c = a.dot(b)
d = np.diag(c)

print(c)
print(d)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
[ 84 216 366]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [11]:
a = np.array([1, 2, 3, 4, 5])

zeros = 3

result = []

#takes every element in a and add it to the result followed by 3 zeros
for x in a:
    result.extend([x] + [0]*zeros)

print(result)

[np.int64(1), 0, 0, 0, np.int64(2), 0, 0, 0, np.int64(3), 0, 0, 0, np.int64(4), 0, 0, 0, np.int64(5), 0, 0, 0]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [12]:
A = np.arange(1,76).reshape(5,5,3)
#print(A)
B = np.arange(1,16).reshape(5,3)
# print(B)
C = A*B
print(C)

[[[   1    4    9]
  [  16   25   36]
  [  49   64   81]
  [ 100  121  144]
  [ 169  196  225]]

 [[  16   34   54]
  [  76  100  126]
  [ 154  184  216]
  [ 250  286  324]
  [ 364  406  450]]

 [[  31   64   99]
  [ 136  175  216]
  [ 259  304  351]
  [ 400  451  504]
  [ 559  616  675]]

 [[  46   94  144]
  [ 196  250  306]
  [ 364  424  486]
  [ 550  616  684]
  [ 754  826  900]]

 [[  61  124  189]
  [ 256  325  396]
  [ 469  544  621]
  [ 700  781  864]
  [ 949 1036 1125]]]


#### 72. How to swap two rows of an array? (★★★)

In [13]:
A = np.arange(1,10).reshape(3,3)
print(A)

A[[0,2]] = A[[2,0]]

print(A)




[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [17]:
#np.bincount counts the number of occurences of non-negative intergers in an array.
A = np.bincount([0,0,1,2,2,2])
print(A)

C = np.array([2,1,3])

A == C

[2 1 3]


array([ True,  True,  True])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [23]:
#The convolve function cobines two signals to produce a third signal that represent their interaction.
#The key(mode = valid) ensures only full windows are used.
A = np.array([1, 2, 3, 4, 5])
w = 2

window = np.ones(w) / w

result = np.convolve(A, window, mode = 'valid')

print(result)

[1.5 2.5 3.5 4.5]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
Z = np.array([1, 2, 3, 4, 5])
rem_rows = len(Z)-2
result = Z[np.arange(rem_rows)[:, None] + [0, 1, 2]]
print(result)
#the rem_rows calculate the number of rows we need to create
#the np.arange creates rows starting with 0 ,1 ,2
#the [:, None] reshapes the array into a 2D array

[[1 2 3]
 [2 3 4]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [35]:
#negating a boolean
bool_arr = np.array([True, False, True])

print(~bool_arr)

#changing the sign of a float
float_arr = np.array([1.5, -1.8, 3.0])

float_arr *= -1

print(float_arr)


[False  True False]
[-1.5  1.8 -3. ]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [37]:
# d = |(x2-x1)(y1-y0) - (x1-x0)(y2-y1)|/sqrt(x2-x1)sqrd + (y2-y1)sqrd

P0 = np.array([[0,0], [1,1]])
P1 = np.array([[1,0], [2,2]])
p = np.array([0.5, 0.5])

d = P1- P0

numerator = np.abs(np.cross(d, P0 - p))

denominator = np.linalg.norm(d, axis=1)

distance = numerator / denominator

print(distance)

[0.5 0. ]


C:\Users\HP ELITEBOOK 840 G6\AppData\Local\Temp\ipykernel_16328\3581606894.py:9: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  numerator = np.abs(np.cross(d, P0 - p))


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
# d = |(x2-x1)(y1-y0) - (x1-x0)(y2-y1)|/sqrt(x2-x1)sqrd + (y2-y1)sqrd

P0 = np.array([[0,0], [1,1]])
P1 = np.array([[1,0], [2,2]])
p = np.array([0.5, 0.5])
#d is the direction vector of each line
d = P1- P0

print(d)

#The cross product of d and difference in(P0 -p) gives the signed area of a parallelogram
#The absolute gives the parraellogram,s area 
numerator = np.abs(np.cross(d, P0 - p))

#for the denominator the np.linalg.norm calculates the norm of a vector which is the magnitude or size.
denominator = np.linalg.norm(d, axis=1)

distance = numerator / denominator

print(distance)

[[1 0]
 [1 1]]
[0.5 0. ]


C:\Users\HP ELITEBOOK 840 G6\AppData\Local\Temp\ipykernel_16328\530566886.py:9: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  numerator = np.abs(np.cross(d, P0 - p))


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
#since Z has 14 members 
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

w = 4

print(len(Z))

result = np.array([Z[i:i+w] for i in range(len(Z)- w+1)])
#starts off with i=0 and so the first = [0: 4] and so = [1,2,3,4] and so onsince w=4 according to the question
#since the range(len(z)- w+1) =  11 that means the loop will run from 0-10 which is 11 steps== 11 slices in total
print(result)

14
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [ ]:
#A matrix rank is the dimension of the vector space generated by its columns so we us the linalg()
#np.linalg.matrix_rank(A) internally computes the singular values of A
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

mat_rank = np.linalg.matrix_rank(A)

print(mat_rank)

2


#### 83. How to find the most frequent value in an array?

In [51]:
Z = np.array([1,2,3,3,4,5,6,6,6,7,8])

result = np.bincount(Z)

max = np.argmax(result)

print(result)

print(max)

[0 1 1 2 1 1 3 1 1]
6


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
#In the for loop range(for i the shape of rows = 8) == 7 and ths same for the column which loops through horizontally creating a 3 by 3 matrix
G = np.arange(1,101).reshape(10,10)
#print(G)

blocks = []

for i in range(G.shape[0] -2):
    for j in range(G.shape[1] - 2):

        block = G[i: i+ 3, j:j+3]
        blocks.append(block)

blocks = np.array(blocks)
print(blocks)

print(len(blocks))


[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[[[  1   2   3]
  [ 11  12  13]
  [ 21  22  23]]

 [[  2   3   4]
  [ 12  13  14]
  [ 22  23  24]]

 [[  3   4   5]
  [ 13  14  15]
  [ 23  24  25]]

 [[  4   5   6]
  [ 14  15  16]
  [ 24  25  26]]

 [[  5   6   7]
  [ 15  16  17]
  [ 25  26  27]]

 [[  6   7   8]
  [ 16  17  18]
  [ 26  27  28]]

 [[  7   8   9]
  [ 17  18  19]
  [ 27  28  29]]

 [[  8   9  10]
  [ 18  19  20]
  [ 28  29  30]]

 [[ 11  12  13]
  [ 21  22  23]
  [ 31  32  33]]

 [[ 12  13  14]
  [ 22  23  24]
  [ 32  33  34]]

 [[ 13  14  15]
  [ 23  24  25]
  [ 33  34  35]]

 [[ 14  15  16]
  [

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
Z = np.array([0,0,5],
             [0,0,0],
             [5,0,0])

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [61]:
#np.matmul computes the matrix product of two arrays following the rules of linear algebra
p, n = 2, 3
matrices = np.array([
    [[1,2,3], [4,5,6], [7,8,9]]
    
])
print(matrices)
vectors = np.array([
    [[1], [2], [3]]
])
print(vectors)
result = np.sum(np.matmul(matrices, vectors), axis=0)

print(result)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1]
  [2]
  [3]]]
[[14]
 [32]
 [50]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [72]:
H = np.arange(1, 257).reshape(16,16)
print(H)

block_size = 4

n = len(H)

#Arranging the array into 4D blocks
J = H.reshape(n//block_size, block_size, n//block_size, block_size)

#print(J)

#sum for axis 1= rows, 3= columns
block_sums = J.sum(axis = (1,3))

print(block_sums)

[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16]
 [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32]
 [ 33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48]
 [ 49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64]
 [ 65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96]
 [ 97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112]
 [113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128]
 [129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144]
 [145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160]
 [161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176]
 [177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192]
 [193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208]
 [209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224]
 [225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
#Rules to play(A live cell with 2 or 3 live neighbours ==> stays alive)
#              (A dead cell with exactly 3 live neighbors becomes alive)
#               otherwise cell dies or remains dead

#### 89. How to get the n largest values of an array (★★★)

In [ ]:
M = np.array([10,6,7,8,9,4,2])
n = 5

#sorts the array in descending order and gives the first 5
largest_values = np.sort(M)[-n:][::-1]

print(largest_values)

[10  9  8  7  6]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
vectors = [np.array([1,2]), np.array([3,4]), np.array([5,6])]

#compute cartesian product
#Create meshgrid with indexing='ij'
grids = np.meshgrid(*vectors, indexing = 'ij')

result = np.stack(grids, axis=-1).reshape(-1, len(vectors))

print(result)

[[1 3 5]
 [1 3 6]
 [1 4 5]
 [1 4 6]
 [2 3 5]
 [2 3 6]
 [2 4 5]
 [2 4 6]]


#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
L = np.array([[1, 200, 20],
              [2, 500, 50],
              [3, 800, 80]
              ])

names = ['id', 'value', 'count']

#T is for transponse since .fromarrays expects a list of columns
#The np.rec provides convenience functions for creating and manipulating arrays
rec_array = np.rec.fromarrays(L.T, names=names)

print(rec_array)

[(1, 200, 20) (2, 500, 50) (3, 800, 80)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [79]:
##using the ** operator
Z = np.arange(1,11)
Z_cubed = Z ** 3
print(Z_cubed)
#using the np.power
Z_cubed2 = np.power(Z,3)
print(Z_cubed2)
#using manual multiplication
Z_cubed3 = Z * Z * Z
print(Z_cubed3)

[   1    8   27   64  125  216  343  512  729 1000]
[   1    8   27   64  125  216  343  512  729 1000]
[   1    8   27   64  125  216  343  512  729 1000]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [81]:
U = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [9, 1, 2],
    [1, 4, 5],
    [6, 2, 3],
    [7, 8, 4],
    [2, 3, 4],
])

T = np.array([
    [1, 2],
    [3, 4]
])

matches = []
for t_row in T:
    matching_arrays = np.array([np.all(np.isin(t_row, u_row)) for u_row in U])
    matching_indices = np.where(matching_arrays)[0]
    matches.append(matching_indices)


print(matches)



[array([0, 3]), array([7])]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
#D = np.arange(1,31).reshape(10,3)
D = np.array([
    [1, 1, 1],
    [1, 2, 1],
    [1, 1, 4],
    [2, 2, 2],
    [1, 3, 1],
    [3, 3, 3],
    [4, 1, 2],
    [5, 5, 5],
    [1, 6, 7],
    [2, 1, 8]
])

#performs element-wise comparison of each row with the first element and gives a boolean
#The np.any checks if any element in the row is true

formula_rows = np.any(D != D[:, [0]], axis=1)

unequal_rows = D[formula_rows]

print(unequal_rows)



[[1 2 1]
 [1 1 4]
 [1 3 1]
 [4 1 2]
 [1 6 7]
 [2 1 8]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [91]:
W =np.array([0,1,2,3,4,5,6,7,8], dtype=np.uint8)

binary_representation = np.unpackbits(W)

array_binary_representation = np.array(binary_representation).reshape(18,4)

print(array_binary_representation)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 1 1]
 [0 0 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 1 0 1]
 [0 0 0 0]
 [0 1 1 0]
 [0 0 0 0]
 [0 1 1 1]
 [0 0 0 0]
 [1 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
Q = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3]
])

#when we set axis=0 tells the Numpy to look along rows
#np.unique returns unique rows 
unique_rows = np.unique(Q, axis=0)

print(unique_rows)

[[1 2 3]
 [4 5 6]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [101]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

#inner product
#i means "loop over the index i" in both vectors
#The -> with nothing after means "sum over i"
#That gives the dot product
inner = np.einsum('i, i->', A, B)
print(inner)

#outer product
#First vector contributes index i, second contributes index j
#Output has indices ij, meaning a matrix
#Thats the outer product
outer = np.einsum('i, j->ij', A, B)
print(outer)

#einsum only handles mutiplicationa and summation, so elementwise sum is not natuarraly done with einsum
#Elementwise Sum
sum_elem = np.einsum('i,i->i', A,B)
print(sum_elem)

#Elementwise Multiplication
#Same index i appears in input and output
#Means "dont sum, just mutiply elementwise and keep index i"
#Thats elementwise multiplication
mul_element = np.einsum('i,i->i', A,B)
print(mul_element)

32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[ 4 10 18]
[ 4 10 18]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
X = np.array([1,2,3,4,5])

Y = np.array([6,7,8,9,10])

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)